# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02fd828c395443774d6a896267150880d41c4e7390f4b8dd4787fc850dc80e43f46e396bfe9bb8709c50c5c80cbfedd9fed55b7c684ec0c085ac5439c828670f

test:
  secret_key_base: 7fedab66ec744153fefea0a4f5e74f832bf267dd46e2d33b9b31331c7d094b1e9b8fcaf2fb9feb783cbb439b6594cdbd0031403246349ac2f557c6180108b35e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
